### ISSUE TITLE
Fallback route docs and code examples misleading about defaults

### ISSUE THREAD

**Issue by wkillerud** [podium-lib/podium-lib.github.io#34]
Version: 4.2.1

On https://podium-lib.io/docs/podlet/fallbacks#defining-a-fallback-route the docs claim

> With a podlet instance you call the fallback function which will return the route from the manifest. By default this is at `/fallback`.

Turns out the default is an empty string, so following the guide doesn't produce the expected result.

Suggested rewording:

> With a podlet instance you call the fallback function, which will return the route configured in the manifest.

Then update the first code example:

```js
const podlet = new Podlet({
  /* ... */
  fallback: '/fallback',
});

const app = express();

app.get(podlet.fallback(), (req, res) => {
    res.status(200).podiumSend("<div>It didn't work :(</div>");
});
```

**Comment by digitalsadhu** [comment]
Good catch. Trying to think where we should fix this. Perhaps just on the [docs source branch](https://github.com/podium-lib/podium-lib.github.io) for now and the fix should carry through to the docs updates in the works

**Comment by wkillerud** [comment]
Can do @digitalsadhu
