### ISSUE TITLE
Make travis deploy updates

### ISSUE THREAD

**Issue by ivarconr** [podium-lib/podium-lib.github.io#5]
Should not travis build and deploy docs every time master changes?

**Comment by trygve-lie** [comment]
We need a build step for that. 

Though; we need a test step also to get greenkeeper updates so we need to keep the test command here I think: https://github.com/podium-lib/podium-lib.github.io/commit/d15fe87388c6a38fc7b5c47e8a09c89ae7b92e49

**Comment by wkillerud** [comment]
Autodeploys are handled by GitHub Actions after #38
